import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import LoginButton from "@/components/LoginButton";
import Header from "@/components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="bg-fuchsia-100">
      <body className="">
        <main className="flex flex-col items-center text-neutral-950 font-mono">
          <Header />
          {children}
        </main>
      </body>
    </html>
  );
}
