import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Logo from "@/components/Logo";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="flex min-h-screen flex-col items-center justify-between p-24">
          <div className="flex flex-col gap-8 z-10 max-w-2xl w-full items-center justify-between font-mono text-sm lg:flex">
            <a
              href="/"
              className="text-2xl text-neutral-200 font-bold flex gap-6"
            >
              {/* <Logo color="#fcf" className="w-8 h-8" /> */}
              cj's brain
              {/* <Logo color="#fcf" className="w-8 h-8" /> */}
            </a>
            {children}
          </div>
        </main>
      </body>
    </html>
  );
}
